<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Impression;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ImpressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your    own custom
 * repository methods below.
 */
class ImpressionRepository extends EntityRepository
{
    /**
     * @param Impression $impression
     */
    public function saveImpression(Impression $impression)
    {
        $this->_em->persist($impression);
        $this->_em->flush();
    }

    /**
     * @param $userId
     *
     * @return Impression[]
     */
    public function getImpressions($userId)
    {
        $impressions = $this->findBy(['userId' => $userId], ['created' => 'DESC']);

        return $impressions;
    }

    /**
     * @param integer $limit
     *
     * @return Impression[]
     */
    public function getLastImpressions($limit)
    {
        $rsm = new ResultSetMapping();
        $query = $this->_em->createQuery(
            "SELECT i.id, i.impression, u.firstName, u.lastName, u.pictureUrl FROM AppBundle:Impression AS i
                  LEFT JOIN AppBundle:User AS u
                  WITH i.user = u.id
                  WHERE i.isApproved = :isApproved
                  ORDER BY i.createdAt DESC",
            $rsm
        );
        $query
            ->setParameter('isApproved', true)
            ->setMaxResults($limit);
        $impressions = $query->getResult();

        return $impressions;
    }
}
