<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Order;
use AppBundle\Entity\Product;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    /**
     * @param int $userId
     *
     * @param \DateTime $validDate
     *
     * @return Product[]
     */
    public function getUserRevealedProducts($userId, $validDate)
    {
        //todo fix this, negrazina koreikia
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder
            ->select('product')
            ->from(Order::class, 'orders')
            ->join(Product::class, 'product')
            ->where('orders.user = :userId AND orders.status = :statusRevealed')
            ->orWhere('orders.user = :userId AND orders.status = :statusNew AND orders.orderedAt > :validDate')
            ->setParameter('userId', $userId)
            ->setParameter('statusRevealed', 'revealed')
            ->setParameter('statusNew', 'new')
            ->setParameter('validDate', $validDate);
        $products = $queryBuilder->getQuery()->getResult();
        $products = $this->_em->getRepository(User::class)->findOneBy(['id' => $userId]);

        return $products->getOrders();
    }

    /**
     * @param Order $order
     */
    public function saveOrder(Order $order)
    {
        $this->_em->persist($order);
        $this->_em->flush();
    }

    /**
     * @param int $userId
     *
     * @return Order[]
     */
    public function getUserRevealedOrders($userId)
    {
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder
            ->select('orders.orderedAt', 'products.title', 'products.description', 'products.supplier')
            ->from('AppBundle:Order', 'orders')
            ->innerJoin(
                'AppBundle:Product',
                'products',
                \Doctrine\ORM\Query\Expr\Join::WITH,
                'orders.product = products.id'
            )
            ->where('orders.user = :user')
            ->andWhere('orders.status = :status')
            ->setParameter('user', $userId)
            ->setParameter('status', 'revealed');
        $orders = $queryBuilder->getQuery()->getResult();

        return $orders;
    }

    /**
     * @param int $userId
     *
     * @return Order[]
     */
    public function getUserSecrets($userId)
    {
        $userSecrets = $this->findBy([
            'user' =>  $userId,
            'status' => 'new'
        ], ['orderedAt' => 'DESC']);

        return $userSecrets;
    }
}
