<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Price;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{
    /**
     * @return Price
     */
    public function getCurrentPrice()
    {
        $now = new \DateTime();
        $rsm = new ResultSetMapping();
        $query = $this->_em
            ->createQuery('SELECT p FROM AppBundle:Price AS p WHERE p.validFrom < :now ORDER BY p.validFrom DESC', $rsm)
            ->setParameter(':now', $now)
            ->setMaxResults(1);

        $result = $query->getResult();
        return $result[0];
    }
}
