<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $usedProducts
     *
     * @param /Datetime $validDate
     *
     * @return array
     */
    public function getUniqueProducts($usedProducts, $validDate)
    {
        if (empty($usedProducts)) {
            array_push($usedProducts, 0);
        }

        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder
            ->select('product.id', 'product.facebookName as name', 'product.gender', 'product.ageMin', 'product.ageMax')
            ->from(Product::class, 'product')
            ->where('product.id NOT IN (:usedProducts)')
            ->andWhere('product.validTo > :validDate')
            ->setParameter('usedProducts', $usedProducts)
            ->setParameter('validDate', $validDate);
        $products = $queryBuilder->getQuery()->getResult();

        return $products;
    }
}
