<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @param array $usedProducts
     * @param \DateTime $validDate
     * @param string $boxSize
     *
     * @return array
     * @internal param $ /Datetime $validDate
     */
    public function getUniqueProducts($usedProducts, $validDate, $boxSize)
    {
        if (empty($usedProducts)) {
            array_push($usedProducts, 0);
        }

        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder
            ->select('product.id', 'product.facebookName as name', 'product.gender', 'product.ageMin', 'product.ageMax')
            ->from(Product::class, 'product')
            ->where('product.id NOT IN (:usedProducts)')
            ->andWhere('product.validTo > :validDate')
            ->andWhere('product.boxSize = :boxSize')
            ->setParameter('usedProducts', $usedProducts)
            ->setParameter('validDate', $validDate)
            ->setParameter('boxSize', $boxSize);
        $products = $queryBuilder->getQuery()->getResult();

        return $products;
    }
}
