<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param User $user
     */
    public function saveUser(User $user)
    {
        $this->_em->persist($user);
        $this->_em->flush();
    }

    /**
     * @return array
     */
    public function countAllUsers()
    {
        $result = $this->_em->getConnection()->executeQuery('
            SELECT COUNT(id) as customers FROM users
        ')->fetchAll();

        return $result[0];
    }
}
