security:
    providers:
        in_memory:
            memory: ~
        secretbox_users:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - 'facebook_authenticator'
            logout:
                path: /logout

    access_control:
        - {path: ^/%locale%/user_profile, roles: ROLE_USER}
        - {path: ^/%locale%/orders, roles: ROLE_USER}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}