security:
    providers:
        in_memory:
            memory: ~
        secretbox_users:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - AppBundle\Service\FacebookAuthenticatorService
            logout:
                path: /logout

    access_control:
        - {path: ^/%locale%/admin, roles: ROLE_ADMIN}
        - {path: ^/%locale%/user, roles: ROLE_USER}
        - {path: ^/%locale%/order, roles: ROLE_USER}
        - {path: ^/%locale%/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}