#parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests}'

    AppBundle\Service\FacebookInfoService:
        arguments:
            - "%facebook_client_id%"
            - "%facebook_client_secret%"
            - "%facebook_graph_api%"

    AppBundle\Service\ProductSelectionService:
        arguments:
            - "%secret_reveal_time%"

    AppBundle\EventListener\PostUserLoginListener:
        tags:
            - {name: kernel.event_listener, event: user.login, method: onUserLoginSaveImage}

    AppBundle\EventListener\RouteErrorRedirectListener:
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
