#parameters:


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests}'


    facebook_authenticator:
        class: AppBundle\Service\FacebookAuthenticator
        autowire: true

#    AppBundle\Service\OrderService:
#        autowire: true

