parameters:


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests}'


    facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true
