#parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests}'

    AppBundle\EventListener\PostUserLoginListener:
        tags:
            - {name: kernel.event_listener, event: user.login, method: onUserLoginSaveImage}


