AppBundle\Entity\Order:
    properties:
        deliveryAddress:
            - NotBlank: {message: message.address.blank}

AppBundle\Entity\Impression:
    properties:
        impression:
            - NotBlank: ~

AppBundle\Entity\User:
    properties:
        email:
            - NotBlank: {message: message.email.invalid}
            - Email:
                checkHost: true
                message: message.email.invalid
        firstName:
            - NotBlank: {message: message.firstname.blank}

        lastName:
            - NotBlank: {message: message.lastname.blank}
