AppBundle\Entity\Order:
    properties:
        deliveryAddress:
            - NotBlank: ~
#            - message: message.no.new.secrets
#        product:
#            - NotNull:
#                message: message.no.new.secrets

AppBundle\Entity\Impression:
    properties:
        impression:
            - NotBlank: ~

AppBundle\Entity\User:
    properties:
        address:
            - NotNull: ~
        email:
            - NotBlank: ~
            - Email:
                checkHost: true
                message: message.no.valid.email
#    todo padaryt validationus visoms reiksmems, uzsakymas draugui