AppBundle\Entity\Order:
    properties:
        deliveryAddress:
            - NotBlank: ~
        productId:
            - NotEqualTo:
                value: 0
                message: message.no.new.secrets

AppBundle\Entity\Impression:
    properties:
        impression:
            - NotBlank: ~